version: '3'
services:
  rundeck:
    container_name: rundeck
    image: anmcarrow/rundeck-ansible
    environment:
      - RDECK_ADMIN_PASS=admin
#      - RDECK_HOST=0.0.0.0      
      - RDECK_PORT=4440
      - RDECK_VERSION=3.0.1-20180803
    ports:
      - "4440:4440"
#     hostname: rundeck.example.net
#     volumes: "/opt/rundeck:/var/lib/rundeck"

